### ISSUE TITLE
Incompatibility with some mods (What Mods are incompatible look comments!)

### ISSUE THREAD

**Issue by Onako2** [fantahund/CubesideMod#5]
The Mod is with some mod incompatible

Logs: https://mclo.gs/nxZksvc

How to reproduce:
1. Install the Modrinth Modpack Neboptimization(LITE or FULL does not matter)
2. Add CubesideMod to the instance
3. Start the game

**Comment by Onako2** [comment]
UPDATE: Found out: 
Incompatibility with Quilted Fabric API
Log: https://mclo.gs/eN9RpSN

**Comment by fantahund** [comment]
The mod needs the normal Fabric API which works with Quilt too which should not break anything. Test if it works if you put the Fabric API in your mod folder. For me it works at least with only Fabric API and Cubeside mod under Quilt

**Comment by Onako2** [comment]
> 

Sadly some mods require the Quilt Fabric API.

**Comment by fantahund** [comment]
Can not you use both at the same time? Sorry, I do not use Quilt, just tested it that way. :D

**Comment by Onako2** [comment]
> 

No Quilt blocks it
